### ISSUE TITLE
Need to add repository info and mod to use forked cache-api.

### ISSUE THREAD

**Issue by gmessner** [gmessner/spring-petclinic#1]
Need to add repositories, distributionManagement, and add set the cache-api dependency version to LATEST.

**Comment by gmessner** [comment]
This work has been completed by PR #2.

**Comment by snicoll** [comment]
Curious here following the pr you submitted to the main repo. Why do you need LATEST?

**Comment by gmessner** [comment]
@snicoll 
This is being done as part of an exercise which required a dependency from this project to be forked and cause this project to be automatically built in Jenkins after the forked dependency project was built in Jenkins. Nothing more than a test of upstream and downstream projects in Jenkins.

BTW, the PR that was submitted to the main repo was done in error, that PR was intended for this repo only.
